SELECT prs.[NPI]
      ,prs.[Gender]
      ,prs.[Credentials]
      ,prs.[Specialty]
	  ,prs.[State] as Abbrev
	  ,isnull(st.[State], 'Not Found') as [State]
	  ,isnull(st.[Population],0) as [Population]
      ,isnull(st.[Deaths],0) as [Deaths]
	  ,prs.[Opioid Prescriber]
      ,prs.[ABILIFY]
      ,prs.[ACETAMINOPHEN CODEINE]
      ,prs.[ACYCLOVIR]
      ,prs.[ADVAIR DISKUS]
      ,prs.[AGGRENOX]
      ,prs.[ALENDRONATE SODIUM]
      ,prs.[ALLOPURINOL]
      ,prs.[ALPRAZOLAM]
      ,prs.[AMIODARONE HCL]
      ,prs.[AMITRIPTYLINE HCL]
      ,prs.[AMLODIPINE BESYLATE]
      ,prs.[AMLODIPINE BESYLATE BENAZEPRIL]
      ,prs.[AMOXICILLIN]
      ,prs.[AMOX TR POTASSIUM CLAVULANATE]
      ,prs.[AMPHETAMINE SALT COMBO]
      ,prs.[ATENOLOL]
      ,prs.[ATORVASTATIN CALCIUM]
      ,prs.[AVODART]
      ,prs.[AZITHROMYCIN]
      ,prs.[BACLOFEN]
      ,prs.[BD ULTRA FINE PEN NEEDLE]
      ,prs.[BENAZEPRIL HCL]
      ,prs.[BENICAR]
      ,prs.[BENICAR HCT]
      ,prs.[BENZTROPINE MESYLATE]
      ,prs.[BISOPROLOL HYDROCHLOROTHIAZIDE]
      ,prs.[BRIMONIDINE TARTRATE]
      ,prs.[BUMETANIDE]
      ,prs.[BUPROPION HCL SR]
      ,prs.[BUPROPION XL]
      ,prs.[BUSPIRONE HCL]
      ,prs.[BYSTOLIC]
      ,prs.[CARBAMAZEPINE]
      ,prs.[CARBIDOPA LEVODOPA]
      ,prs.[CARISOPRODOL]
      ,prs.[CARTIA XT]
      ,prs.[CARVEDILOL]
      ,prs.[CEFUROXIME]
      ,prs.[CELEBREX]
      ,prs.[CEPHALEXIN]
      ,prs.[CHLORHEXIDINE GLUCONATE]
      ,prs.[CHLORTHALIDONE]
      ,prs.[CILOSTAZOL]
      ,prs.[CIPROFLOXACIN HCL]
      ,prs.[CITALOPRAM HBR]
      ,prs.[CLINDAMYCIN HCL]
      ,prs.[CLOBETASOL PROPIONATE]
      ,prs.[CLONAZEPAM]
      ,prs.[CLONIDINE HCL]
      ,prs.[CLOPIDOGREL]
      ,prs.[CLOTRIMAZOLE BETAMETHASONE]
      ,prs.[COLCRYS]
      ,prs.[COMBIVENT RESPIMAT]
      ,prs.[CRESTOR]
      ,prs.[CYCLOBENZAPRINE HCL]
      ,prs.[DEXILANT]
      ,prs.[DIAZEPAM]
      ,prs.[DICLOFENAC SODIUM]
      ,prs.[DICYCLOMINE HCL]
      ,prs.[DIGOX]
      ,prs.[DIGOXIN]
      ,prs.[DILTIAZEM 24HR CD]
      ,prs.[DILTIAZEM 24HR ER]
      ,prs.[DILTIAZEM ER]
      ,prs.[DILTIAZEM HCL]
      ,prs.[DIOVAN]
      ,prs.[DIPHENOXYLATE ATROPINE]
      ,prs.[DIVALPROEX SODIUM]
      ,prs.[DIVALPROEX SODIUM ER]
      ,prs.[DONEPEZIL HCL]
      ,prs.[DORZOLAMIDE TIMOLOL]
      ,prs.[DOXAZOSIN MESYLATE]
      ,prs.[DOXEPIN HCL]
      ,prs.[DOXYCYCLINE HYCLATE]
      ,prs.[DULOXETINE HCL]
      ,prs.[ENALAPRIL MALEATE]
      ,prs.[ESCITALOPRAM OXALATE]
      ,prs.[ESTRADIOL]
      ,prs.[EXELON]
      ,prs.[FAMOTIDINE]
      ,prs.[FELODIPINE ER]
      ,prs.[FENOFIBRATE]
      ,prs.[FENTANYL]
      ,prs.[FINASTERIDE]
      ,prs.[FLOVENT HFA]
      ,prs.[FLUCONAZOLE]
      ,prs.[FLUOXETINE HCL]
      ,prs.[FLUTICASONE PROPIONATE]
      ,prs.[FUROSEMIDE]
      ,prs.[GABAPENTIN]
      ,prs.[GEMFIBROZIL]
      ,prs.[GLIMEPIRIDE]
      ,prs.[GLIPIZIDE]
      ,prs.[GLIPIZIDE ER]
      ,prs.[GLIPIZIDE XL]
      ,prs.[GLYBURIDE]
      ,prs.[HALOPERIDOL]
      ,prs.[HUMALOG]
      ,prs.[HYDRALAZINE HCL]
      ,prs.[HYDROCHLOROTHIAZIDE]
      ,prs.[HYDROCODONE ACETAMINOPHEN]
      ,prs.[HYDROCORTISONE]
      ,prs.[HYDROMORPHONE HCL]
      ,prs.[HYDROXYZINE HCL]
      ,prs.[IBANDRONATE SODIUM]
      ,prs.[IBUPROFEN]
      ,prs.[INSULIN SYRINGE]
      ,prs.[IPRATROPIUM BROMIDE]
      ,prs.[IRBESARTAN]
      ,prs.[ISOSORBIDE MONONITRATE ER]
      ,prs.[JANTOVEN]
      ,prs.[JANUMET]
      ,prs.[JANUVIA]
      ,prs.[KETOCONAZOLE]
      ,prs.[KLOR CON 10]
      ,prs.[KLOR CON M10]
      ,prs.[KLOR CON M20]
      ,prs.[LABETALOL HCL]
      ,prs.[LACTULOSE]
      ,prs.[LAMOTRIGINE]
      ,prs.[LANSOPRAZOLE]
      ,prs.[LANTUS]
      ,prs.[LANTUS SOLOSTAR]
      ,prs.[LATANOPROST]
      ,prs.[LEVEMIR]
      ,prs.[LEVEMIR FLEXPEN]
      ,prs.[LEVETIRACETAM]
      ,prs.[LEVOFLOXACIN]
      ,prs.[LEVOTHYROXINE SODIUM]
      ,prs.[LIDOCAINE]
      ,prs.[LISINOPRIL]
      ,prs.[LISINOPRIL HYDROCHLOROTHIAZIDE]
      ,prs.[LITHIUM CARBONATE]
      ,prs.[LORAZEPAM]
      ,prs.[LOSARTAN HYDROCHLOROTHIAZIDE]
      ,prs.[LOSARTAN POTASSIUM]
      ,prs.[LOVASTATIN]
      ,prs.[LOVAZA]
      ,prs.[LUMIGAN]
      ,prs.[LYRICA]
      ,prs.[MECLIZINE HCL]
      ,prs.[MELOXICAM]
      ,prs.[METFORMIN HCL]
      ,prs.[METFORMIN HCL ER]
      ,prs.[METHADONE HCL]
      ,prs.[METHOCARBAMOL]
      ,prs.[METHOTREXATE]
      ,prs.[METHYLPREDNISOLONE]
      ,prs.[METOCLOPRAMIDE HCL]
      ,prs.[METOLAZONE]
      ,prs.[METOPROLOL SUCCINATE]
      ,prs.[METOPROLOL TARTRATE]
      ,prs.[METRONIDAZOLE]
      ,prs.[MIRTAZAPINE]
      ,prs.[MONTELUKAST SODIUM]
      ,prs.[MORPHINE SULFATE]
      ,prs.[MORPHINE SULFATE ER]
      ,prs.[MUPIROCIN]
      ,prs.[NABUMETONE]
      ,prs.[NAMENDA]
      ,prs.[NAMENDA XR]
      ,prs.[NAPROXEN]
      ,prs.[NASONEX]
      ,prs.[NEXIUM]
      ,prs.[NIACIN ER]
      ,prs.[NIFEDICAL XL]
      ,prs.[NIFEDIPINE ER]
      ,prs.[NITROFURANTOIN MONO MACRO]
      ,prs.[NITROSTAT]
      ,prs.[NORTRIPTYLINE HCL]
      ,prs.[NOVOLOG]
      ,prs.[NOVOLOG FLEXPEN]
      ,prs.[NYSTATIN]
      ,prs.[OLANZAPINE]
      ,prs.[OMEPRAZOLE]
      ,prs.[ONDANSETRON HCL]
      ,prs.[ONDANSETRON ODT]
      ,prs.[ONGLYZA]
      ,prs.[OXCARBAZEPINE]
      ,prs.[OXYBUTYNIN CHLORIDE]
      ,prs.[OXYBUTYNIN CHLORIDE ER]
      ,prs.[OXYCODONE ACETAMINOPHEN]
      ,prs.[OXYCODONE HCL]
      ,prs.[OXYCONTIN]
      ,prs.[PANTOPRAZOLE SODIUM]
      ,prs.[PAROXETINE HCL]
      ,prs.[PHENOBARBITAL]
      ,prs.[PHENYTOIN SODIUM EXTENDED]
      ,prs.[PIOGLITAZONE HCL]
      ,prs.[POLYETHYLENE GLYCOL 3350]
      ,prs.[POTASSIUM CHLORIDE]
      ,prs.[PRADAXA]
      ,prs.[PRAMIPEXOLE DIHYDROCHLORIDE]
      ,prs.[PRAVASTATIN SODIUM]
      ,prs.[PREDNISONE]
      ,prs.[PREMARIN]
      ,prs.[PRIMIDONE]
      ,prs.[PROAIR HFA]
      ,prs.[PROMETHAZINE HCL]
      ,prs.[PROPRANOLOL HCL]
      ,prs.[PROPRANOLOL HCL ER]
      ,prs.[QUETIAPINE FUMARATE]
      ,prs.[QUINAPRIL HCL]
      ,prs.[RALOXIFENE HCL]
      ,prs.[RAMIPRIL]
      ,prs.[RANEXA]
      ,prs.[RANITIDINE HCL]
      ,prs.[RESTASIS]
      ,prs.[RISPERIDONE]
      ,prs.[ROPINIROLE HCL]
      ,prs.[SEROQUEL XR]
      ,prs.[SERTRALINE HCL]
      ,prs.[SIMVASTATIN]
      ,prs.[SOTALOL]
      ,prs.[SPIRIVA]
      ,prs.[SPIRONOLACTONE]
      ,prs.[SUCRALFATE]
      ,prs.[SULFAMETHOXAZOLE TRIMETHOPRIM]
      ,prs.[SUMATRIPTAN SUCCINATE]
      ,prs.[SYMBICORT]
      ,prs.[SYNTHROID]
      ,prs.[TAMSULOSIN HCL]
      ,prs.[TEMAZEPAM]
      ,prs.[TERAZOSIN HCL]
      ,prs.[TIMOLOL MALEATE]
      ,prs.[TIZANIDINE HCL]
      ,prs.[TOLTERODINE TARTRATE ER]
      ,prs.[TOPIRAMATE]
      ,prs.[TOPROL XL]
      ,prs.[TORSEMIDE]
      ,prs.[TRAMADOL HCL]
      ,prs.[TRAVATAN Z]
      ,prs.[TRAZODONE HCL]
      ,prs.[TRIAMCINOLONE ACETONIDE]
      ,prs.[TRIAMTERENE HYDROCHLOROTHIAZID]
      ,prs.[VALACYCLOVIR]
      ,prs.[VALSARTAN]
      ,prs.[VALSARTAN HYDROCHLOROTHIAZIDE]
      ,prs.[VENLAFAXINE HCL]
      ,prs.[VENLAFAXINE HCL ER]
      ,prs.[VENTOLIN HFA]
      ,prs.[VERAPAMIL ER]
      ,prs.[VESICARE]
      ,prs.[VOLTAREN]
      ,prs.[VYTORIN]
      ,prs.[WARFARIN SODIUM]
      ,prs.[XARELTO]
      ,prs.[ZETIA]
      ,prs.[ZIPRASIDONE HCL]
      ,prs.[ZOLPIDEM TARTRATE]

  FROM 
       [ECE].[dbo].[cms-prescriber-info] prs 
	   LEFT JOIN [ECE].[dbo].[cms-overdoses] st ON st.[Abbrev] = prs.[State]




/* Stage opioids.csv file to one column remove - / and duplicates */
TRUNCATE TABLE [cms-opioids]
INSERT INTO [cms-opioids]
SELECT replace([Drug Name],'-',' ') as [Drug Name]
FROM [ECE].[dbo].[cms-opioids-stg]
UNION
SELECT replace([Generic Name],'/',' ') as [Drug Name]
FROM [ECE].[dbo].[cms-opioids-stg]

/* Column names for data set */
SELECT name as [Prescriber Drugs]
FROM sys.columns sc
WHERE
 sc.name <> 'NPI'
and SUBSTRING(sc.name,2,1) <> LOWER(SUBSTRING(sc.name,2,1)) COLLATE Latin1_General_CS_AI
and object_id = 402100473 -- cms-prescriber-info table


truncate table [cms-clusters]
insert into [cms-clusters]
SELECT replace([pain medicine],'.',' ') as Drug,
	  'pain medicine' as [Use]
  FROM [ECE].[dbo].[cms-clusters-stg]
UNION
SELECT replace([sleep/anxiety],'.',' ') as Drug,
       'sleep/anxiety' as [Use]
FROM [ECE].[dbo].[cms-clusters-stg]



SELECT [Drug Name] as [Opioids/Opiates]
  FROM [ECE].[dbo].[cms-opioids]
UNION 
SELECT [Drug] as [Opioids/Opiates]
  FROM [ECE].[dbo].[cms-clusters]





